#include "next/ops/ops_workspace.h"

#include <algorithm>
#include <chrono>
#include <filesystem>
#include <fstream>
#include <sstream>

namespace Next {
namespace {

namespace fs = std::filesystem;

const char* kPolicyPy = R"(import json


def score_route(order, route):
    score = route["travel_time"]
    score += route["camera_risk"] * 3
    score += route["vehicle_cost"] * 2
    score -= route["crowd_cover"]
    return score


def choose_route(order, routes):
    return min(routes, key=lambda route: score_route(order, route))


if __name__ == "__main__":
    with open("city_graph.json", "r", encoding="utf-8") as f:
        city = json.load(f)

    order = city["orders"][0]
    route = choose_route(order, city["routes"])
    print(json.dumps({"order_id": order["id"], "route_id": route["id"]}))
)";

const char* kOrdersLog = R"(00:11:22 order.demo witness_transfer queued
00:12:04 camera.cam-14 maintenance_window pending
00:13:37 robot.r-7 route_locked depot_west
00:14:18 vehicle.van-22 smart_link available cost=4
)";

const char* kCityGraphJson = R"({
  "orders": [
    {
      "id": "order.demo",
      "witness_risk": 71,
      "deadline_min": 18
    }
  ],
  "routes": [
    {
      "id": "route.metro-service",
      "travel_time": 13,
      "camera_risk": 5,
      "vehicle_cost": 0,
      "crowd_cover": 7
    },
    {
      "id": "route.smart-van",
      "travel_time": 9,
      "camera_risk": 3,
      "vehicle_cost": 4,
      "crowd_cover": 2
    },
    {
      "id": "route.loading-docks",
      "travel_time": 17,
      "camera_risk": 1,
      "vehicle_cost": 1,
      "crowd_cover": 6
    }
  ]
}
)";

const char* kOpsToml = R"([workspace]
scenario = "maintenance-window"
version = 1

[permissions]
read = ["orders.log", "city_graph.json"]
write = ["policy.py"]
network = false

[budget]
scan_units = 12
vehicle_tokens = 1
llm_tokens = 0
)";

const char* kReadme = R"(# Maintenance Window

This workspace is generated by the HackOps headless demo.

Edit `policy.py`, inspect `orders.log` and `city_graph.json`, then run the
future simulation command to submit a route policy back to the game world.
)";

std::string SanitizeSnapshotName(const std::string& name) {
    std::string out;
    for (const char ch : name) {
        const bool ok = (ch >= 'a' && ch <= 'z') ||
            (ch >= 'A' && ch <= 'Z') ||
            (ch >= '0' && ch <= '9') ||
            ch == '-' ||
            ch == '_';
        out.push_back(ok ? ch : '-');
    }
    if (out.empty()) {
        out = "snapshot";
    }
    return out;
}

std::string TimestampSuffix() {
    const auto now = std::chrono::system_clock::now().time_since_epoch();
    const auto millis = std::chrono::duration_cast<std::chrono::milliseconds>(now).count();
    return std::to_string(millis);
}

} // namespace

bool OpsWorkspace::Initialize(const OpsWorkspaceConfig& config) {
    lastError_.clear();
    rootPath_ = config.rootPath.empty() ? DefaultHackOpsWorkspacePath() : config.rootPath;
    scenarioId_ = config.scenarioId.empty() ? "maintenance-window" : config.scenarioId;
    initialized_ = true;

    if (config.overwrite && !Reset()) {
        return false;
    }

    return EnsureSeedFiles();
}

bool OpsWorkspace::Reset() {
    if (rootPath_.empty()) {
        SetError("workspace root is empty");
        return false;
    }

    std::error_code ec;
    fs::remove_all(rootPath_, ec);
    if (ec) {
        SetError("failed to remove workspace: " + ec.message());
        return false;
    }

    fs::create_directories(rootPath_, ec);
    if (ec) {
        SetError("failed to create workspace: " + ec.message());
        return false;
    }

    return true;
}

bool OpsWorkspace::EnsureSeedFiles() {
    if (rootPath_.empty()) {
        SetError("workspace root is empty");
        return false;
    }

    std::error_code ec;
    fs::create_directories(rootPath_, ec);
    if (ec) {
        SetError("failed to create workspace: " + ec.message());
        return false;
    }

    return WriteTextFile("ops.toml", kOpsToml, false) &&
        WriteTextFile("policy.py", kPolicyPy, false) &&
        WriteTextFile("orders.log", kOrdersLog, false) &&
        WriteTextFile("city_graph.json", kCityGraphJson, false) &&
        WriteTextFile("README.md", kReadme, false);
}

bool OpsWorkspace::CreateSnapshot(const std::string& name, OpsWorkspaceSnapshot* outSnapshot) const {
    if (rootPath_.empty()) {
        SetError("workspace root is empty");
        return false;
    }

    const std::string snapshotName = SanitizeSnapshotName(name) + "-" + TimestampSuffix();
    const std::string snapshotRoot = AbsolutePath("snapshots/" + snapshotName);

    std::error_code ec;
    fs::create_directories(snapshotRoot, ec);
    if (ec) {
        SetError("failed to create snapshot: " + ec.message());
        return false;
    }

    std::vector<OpsWorkspaceFile> copiedFiles;
    for (const auto& file : ListFiles()) {
        if (file.relativePath.rfind("snapshots/", 0) == 0) {
            continue;
        }
        if (!CopyFileToSnapshot(file.relativePath, snapshotRoot)) {
            return false;
        }
        copiedFiles.push_back(file);
    }

    if (outSnapshot) {
        outSnapshot->name = snapshotName;
        outSnapshot->path = snapshotRoot;
        outSnapshot->files = copiedFiles;
    }

    return true;
}

std::vector<OpsWorkspaceFile> OpsWorkspace::ListFiles() const {
    std::vector<OpsWorkspaceFile> files;
    if (rootPath_.empty() || !fs::exists(rootPath_)) {
        return files;
    }

    std::error_code ec;
    for (const auto& entry : fs::recursive_directory_iterator(rootPath_, ec)) {
        if (ec || !entry.is_regular_file()) {
            continue;
        }

        const auto relative = fs::relative(entry.path(), rootPath_, ec);
        if (ec) {
            continue;
        }

        OpsWorkspaceFile file;
        file.relativePath = relative.generic_string();
        file.sizeBytes = entry.file_size(ec);
        if (ec) {
            file.sizeBytes = 0;
        }
        files.push_back(file);
    }

    std::sort(files.begin(), files.end(), [](const OpsWorkspaceFile& lhs, const OpsWorkspaceFile& rhs) {
        return lhs.relativePath < rhs.relativePath;
    });
    return files;
}

bool OpsWorkspace::WriteTextFile(const std::string& relativePath, const std::string& content, bool overwrite) {
    const std::string path = AbsolutePath(relativePath);
    if (!overwrite && fs::exists(path)) {
        return true;
    }

    std::error_code ec;
    fs::create_directories(fs::path(path).parent_path(), ec);
    if (ec) {
        SetError("failed to create parent directory for " + relativePath + ": " + ec.message());
        return false;
    }

    std::ofstream out(path, std::ios::binary);
    if (!out) {
        SetError("failed to open " + relativePath + " for writing");
        return false;
    }

    out << content;
    if (!out) {
        SetError("failed to write " + relativePath);
        return false;
    }

    return true;
}

bool OpsWorkspace::CopyFileToSnapshot(const std::string& relativePath, const std::string& snapshotRoot) const {
    const fs::path source = AbsolutePath(relativePath);
    const fs::path target = fs::path(snapshotRoot) / fs::path(relativePath);

    std::error_code ec;
    fs::create_directories(target.parent_path(), ec);
    if (ec) {
        SetError("failed to create snapshot parent for " + relativePath + ": " + ec.message());
        return false;
    }

    fs::copy_file(source, target, fs::copy_options::overwrite_existing, ec);
    if (ec) {
        SetError("failed to copy snapshot file " + relativePath + ": " + ec.message());
        return false;
    }

    return true;
}

std::string OpsWorkspace::AbsolutePath(const std::string& relativePath) const {
    return (fs::path(rootPath_) / fs::path(relativePath)).lexically_normal().string();
}

void OpsWorkspace::SetError(const std::string& message) const {
    lastError_ = message;
}

std::string DefaultHackOpsWorkspacePath() {
    return (fs::temp_directory_path() / "next-hackops" / "maintenance-window").string();
}

} // namespace Next
